Fixed type #83
OpenMined/threepio pull request #100
Opened 2020-06-30 11:21 UTC by ramesht007

## Description
Wrote detailed Inline documentations for tf_spider.py to attend to issue #83  in the Threepio project.

2020-06-30 14:17 UTC, Nolski requested changes
This looks great, just a few things to fix and then it should be ready to merge. Great work!

2020-06-30 14:17 UTC, Nolski commented on docs-crawler/docs/docs/spiders/tf_spider.py
> +    # Regex rules for compiling a string to a Regex object.
The comment here should explain what the regex rules are. Here the rules will match on two groups and expects a function call similar to below
`foo.bar(arg1, arg2)`
First group is `foo.bar`.
Second group is `arg1, arg2`

2020-06-30 14:17 UTC, Nolski commented on docs-crawler/docs/docs/spiders/tf_spider.py
> +        # text = remove_tags(function_header.get())\
I think this line can be removed :)

2020-06-30 14:19 UTC, ramesht007 commented on docs-crawler/docs/docs/spiders/tf_spider.py
> +        # text = remove_tags(function_header.get())\
ok

2020-07-01 08:01 UTC, Nolski approved these changes
![](https://media.giphy.com/media/yyZRSvISN1vvW/giphy.gif)

2020-07-01 08:01 UTC, merged