Inline docs for threepio.py
OpenMined/threepio pull request #145
Opened 2021-01-18 09:44 UTC by Praful932

## Description
- Added inline documentation and docstrings for threepio.py
- Fixed flake8 warnings
- removed deprecated function parameters

Resolves #69 

> I have followed restructured text format to document the code same as Pysyft docs

## Affected Dependencies
None

## How has this been tested?
Passed pytest and flake8 as described in the workflow file.

## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [X] My changes are covered by tests

2021-01-19 12:49 UTC, Nolski requested changes
Just one small change and I'll merge :)

2021-01-19 12:49 UTC, Nolski commented on pythreepio/pythreepio/threepio.py
> +    :param framework: Framework to convert to
Something more descriptive might be `Reference to package that represents to_lang`

2021-01-20 05:59 UTC, Praful932 commented on pythreepio/pythreepio/threepio.py
> +    :param framework: Framework to convert to
Done

2021-01-20 06:02 UTC, Praful932 commented
@Nolski The [Openmined styleguide](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) mentions Google Doc style while Pysyft uses rst format for docs. To keep it consistent with Pysyft I used rst format, let me know if I need to change the doc style

2021-01-25 03:18 UTC, ramesht007 approved these changes

2021-01-25 03:19 UTC, ramesht007 commented
Looks good to me :)
Thanks, @Praful932

2021-01-25 09:52 UTC, Nolski commented
![](https://media.giphy.com/media/7OsTzueI8eRzo56R56/giphy.gif)

2021-01-25 09:53 UTC, Nolski approved these changes
![](https://media.giphy.com/media/7OsTzueI8eRzo56R56/giphy-downsized.gif)

2021-01-25 09:53 UTC, merged