Add version attribute for each spider (#3)
OpenMined/threepio pull request #8
Opened 2020-01-19 16:15 UTC by AmrMKayid

Currently the docs version is static

2020-01-20 14:01 UTC, Nolski requested changes

2020-01-20 14:01 UTC, Nolski commented on docs-crawler/docs/docs/pipelines.py
> +        output_dir = f"output/{spider.version}"
It looks like the the current output format would look like 

`output/2.1/tf.json`

Which might be a bit confusing as there is little grouping.

Perhaps instead we could do

`output/tf/2.1.json` which might make grouping a bit simpler. What do you think?

2020-01-20 17:34 UTC, AmrMKayid commented on docs-crawler/docs/docs/pipelines.py
> +        output_dir = f"output/{spider.version}"
Yeah right, I was thinking about this grouping!
I think your idea is much better, will update the file now

2020-01-21 08:33 UTC, Nolski approved these changes
![](https://media.giphy.com/media/26ufq9mryvc5HI27m/giphy.gif)

2020-01-21 08:33 UTC, merged